# Generated by Django 6.0.1 on 2026-01-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
