# Generated by Django 6.0.1 on 2026-02-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filiere',
            name='code',
            field=models.CharField(choices=[('AD', 'Analytique des Données'), ('IDAI', "Ingénierie de Développement d'Applications Informatiques"), ('SSD', 'Statistique et Sciences des Données'), ('MIDS', 'Mathématiques & Informatique Décisionnelles'), ('GI', 'Génie Informatique'), ('GIND', 'Génie Industriel'), ('MBD', 'Mobiquité & Big Data'), ('SIM', 'Systèmes Informatiques & Mobiles'), ('AISD', 'Intelligence Artificielle et Sciences de Données'), ('GC', 'Génie Civil'), ('GENE', 'Génie Énergétique')], max_length=20, unique=True),
        ),
    ]
