# Generated by Django 6.0.1 on 2026-01-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_reservationrequest_created_at_teacherunavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='What is this course about?', null=True),
        ),
    ]
